apiVersion: batch/v1
kind: Job
metadata:
  name: tf-benchmark
spec:
  template:
    spec:
      volumes:
        - name: config-vol
          hostPath:
            path: /tmp/mlperf/configs
        - name: output-vol
          hostPath:
            path: /tmp/mlperf/outputs
      containers:
      - name: tf-benchmark
        image: ciscoai/mlperf-inference-tf-1.15:kubecon-eu-2020
        command: ["scripts/run.sh", "tf", "ssd-mobilenet", "cpu", "--scenario=SingleStream"]
        volumeMounts:
        - name: config-vol
          mountPath: /mlperf/configs
        - name: output-vol
          mountPath: /mlperf/outputs
      restartPolicy: Never
  backoffLimit: 0
